Repository ArthurVillette/SAE_Crypto, pull requests merged in 2023-12, with the labels that each got.

#18 merge de la branche Feature/cass brut dans la branche develop
  decryptage.py
  test.py
Labels: developpement

#21 merge de Feat/cassage_astucieux_sdes dans develop
  decryptage.py
  test.py
Labels: developpement

#22 Feat/graphe to developp
  graphe.py
Labels: documentation

#25 Feat/aes to developp
  decryptage.py
  test.py
Labels: developpement

#26 fix: ajout des graphe de cryptage, décryptage
  arsene_lupin_extrait.txt
  graphe.py
Labels: documentation

#27 fix: separation du code to developp
  src/AES.py
  src/DES.py
  src/SDES.py
  src/graphe.py
  src/partie1_crypto.py
  src/test.py
Labels: refactoring

#29 fix/ du graphe et des test to developp
  src/graphe.py
  src/partie1_crypto.py
  src/test.py
  txt/arsene_lupin_extrait.txt
  txt/indice1_chiffre.txt
  txt/indice2_chiffre.txt
  txt/indice3_chiffre.txt
  txt/indice3_chiffre_correct.txt
  txt/motCrypteTest.txt
Labels: bug

#31 fix: fonctionnement des graphes to developp
  src/graphe.py
Labels: bug, documentation, refactoring

#32 Merge de la branche Feat/reseau dans develop
  src/AES.py
  src/reseau.py
  src/test.py
  traces/trace_sae.cap
Labels: developpement

#33 Merge de la branche Doc/docstring dans develop
  readme.md
  src/AES.py
  src/SAE_Crypto.ipynb
  src/SDES.py
  src/graphe.py
  src/partie1_crypto.py
  src/reseau.py
Labels: documentation

#34 feat/ ajout du fichier requirement.txt
  requirements.txt
Labels: documentation

#35 Developp to main
  SAE_Crypto.pdf
  images/rossignol1.bmp
  images/rossignol2.bmp
  readme.md
  requirements.txt
  src/AES.py
  src/DES.py
  src/SAE_Crypto.ipynb
  src/SDES.py
  src/graphe.py
  src/image.py
  src/partie1_crypto.py
  src/reseau.py
  src/test.py
  test.py
  traces/trace_sae.cap
  txt/arsene_lupin_extrait.txt
  txt/indice1_chiffre.txt
  txt/indice2_chiffre.txt
  txt/indice3_chiffre.txt
  txt/indice3_chiffre_correct.txt
  txt/motCrypteTest.txt
Labels: bug, documentation, developpement
